import type { NextPage } from 'next'
import {Header} from "../../../components/Header/Header";
import styles from "../../../styles/instruments.module.css";
import Head from "next/head";
import {useRouter} from "next/router";

const instruments: NextPage = () => {
    const req = useRouter();

    return(
        <div className={ styles.container }>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={ styles.main }>
                <Header />
                <div className={ styles.contentBlock }></div>
            </main>
        </div>
    )
}

export default instruments;